### 
# base_trainer schema
# Configured to poison and train a ResNet on the CIFAR-10 dataset.
# Outputs the .pth of a trained model
###

[base_trainer]
output = "string: Path to .pth file."
model = "string: (r18 / r32). For ResNet-18 or ResNet-32"
trainer = "string: (sgd / ranger). Specifies optimizer. "
source_label = "int: {0,1,...,9}. Specifies label to mimic"
target_label = "int: {0,1,...,9}. Specifies label to attack"
poisoner = "string: Form: {{1,2,3}xp, {1,2}xs, {1,4}xl}. Integer resembles number of attacks and string represents type"
poisons = "int: {0,1,...,infty}. Specifies number of poisons to generate"

[OPTIONAL]
variant = "string: Form: {model}_{hyperparam string}. Represents .npy file to consume from data/ when doing label consistent"
reduce_amplitude = "float: {[0, 1], -1.0}. Specifies amplitude reduction for label consistent. -1.0 if none"